[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
bracket_spacing = true
line_length = 100
multiline_func_header = "all"
number_underscore="thousands"

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
