[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[fmt]
bracket_spacing = true
line_length = 100
multiline_func_header = "all"
number_underscore="thousands"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/d6194b452e6c4e0cb5f32eadc72237fb"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
